// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using addressbook_backend.Context;

#nullable disable

namespace addressbook_backend.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("addressbook_backend.Models.Contact", b =>
                {
                    b.Property<int>("contactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<string>("cellPhone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("contactId");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            contactId = 1,
                            address = "Address: 1",
                            age = 21,
                            cellPhone = "Cellphone: 9123456",
                            lastName = "Last Name: 1",
                            name = "Contact Name: 1"
                        },
                        new
                        {
                            contactId = 2,
                            address = "Address: 2",
                            age = 22,
                            cellPhone = "Cellphone: 9234567",
                            lastName = "Last Name: 2",
                            name = "Contact Name: 2"
                        },
                        new
                        {
                            contactId = 3,
                            address = "Address: 3",
                            age = 23,
                            cellPhone = "Cellphone: 9345678",
                            lastName = "Last Name: 3",
                            name = "Contact Name: 3"
                        },
                        new
                        {
                            contactId = 4,
                            address = "Address: 4",
                            age = 24,
                            cellPhone = "Cellphone: 9456789",
                            lastName = "Last Name: 4",
                            name = "Contact Name: 4"
                        },
                        new
                        {
                            contactId = 5,
                            address = "Address: 5",
                            age = 25,
                            cellPhone = "Cellphone: 95678910",
                            lastName = "Last Name: 5",
                            name = "Contact Name: 5"
                        },
                        new
                        {
                            contactId = 6,
                            address = "Address: 6",
                            age = 26,
                            cellPhone = "Cellphone: 967891011",
                            lastName = "Last Name: 6",
                            name = "Contact Name: 6"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
